name: ez_custom_scroll_view
description: A crash-safe CustomScrollView that automatically handles unbounded constraints in any direction.
version: 0.0.2
homepage: https://github.com/Evgenii-Zinner/ez-custom-scroll-view
repository: https://github.com/Evgenii-Zinner/ez-custom-scroll-view
issue_tracker: https://github.com/Evgenii-Zinner/ez-custom-scroll-view/issues
documentation: https://flutter.ezinner.com/ez_custom_scroll_view
topics:
  - flutter
  - ez-flutter
  - scrollview
  - layout
  - slivers
funding:
  - https://github.com/sponsors/Evgenii-Zinner/
  - https://thanks.dev/u/gh/evgenii-zinner
  - https://buymeacoffee.com/evgeniizinner

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
